version: '2'

services:

  #  The Application
  app:
    container_name: chefmaster
    build:
      context: ./
      dockerfile: development/app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
      - ./storage/app/public:/var/www/public/storage
    ports:
      - 8990:80

  # The Database
  database:
    container_name: mysql_database
    image: mysql:8
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=chefmaster"
      - "MYSQL_USER=chefmaster"
      - "MYSQL_PASSWORD=Chefmaster1@"
      - "MYSQL_ROOT_PASSWORD=toor"
    ports:
      - 8991:3306

    # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: